runtime: go115
instance_class: F1
automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
env_variables:
  APPENGINEDEMO_GCP_PROJECT_ID: ${GCP_PROJECT_ID}
  APPENGINEDEMO_SHEETS_KEY: ${GOOGLE_SHEETS_KEY}
  APPENGINEDEMO_SHEETS_NAME: ${GOOGLE_SHEETS_SHEET_NAME}
